package main

import "fmt"

// Kind is the type of artifact the scaffold can generate.
type Kind string

const (
	KindHandler    Kind = "handler"
	KindMiddleware Kind = "middleware"
	KindPackage    Kind = "package"
)

// Kinds is the canonical ordered list shown in the picker.
var Kinds = []Kind{KindHandler, KindMiddleware, KindPackage}

// Spec describes one generation request.
type Spec struct {
	Kind Kind
	Name string // lowercase identifier (e.g. "users", "ratelimit")
}

// Path returns the relative file path the spec writes to. Caller joins
// it with the repo root.
func (s Spec) Path() string {
	switch s.Kind {
	case KindHandler:
		return fmt.Sprintf("internal/handlers/%s.go", s.Name)
	case KindMiddleware:
		return fmt.Sprintf("internal/middleware/%s.go", s.Name)
	case KindPackage:
		return fmt.Sprintf("internal/%s/%s.go", s.Name, s.Name)
	}
	return ""
}

// Render produces the file contents for the spec.
func (s Spec) Render() string {
	switch s.Kind {
	case KindHandler:
		return renderHandler(s.Name)
	case KindMiddleware:
		return renderMiddleware(s.Name)
	case KindPackage:
		return renderPackage(s.Name)
	}
	return ""
}

func renderHandler(name string) string {
	exported := capitalize(name)
	return fmt.Sprintf(`package handlers

import "net/http"

// %s returns an http.HandlerFunc for the %s endpoint.
func %s() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}
}
`, exported, name, exported)
}

func renderMiddleware(name string) string {
	exported := capitalize(name)
	return fmt.Sprintf(`package middleware

import "net/http"

// %s wraps an http.Handler with the %s middleware behavior.
func %s(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
	})
}
`, exported, name, exported)
}

func renderPackage(name string) string {
	return fmt.Sprintf(`// Package %s is a stub generated by cmd/scaffold.
package %s
`, name, name)
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]-32) + s[1:]
}
