package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Preset is one of the named configuration starting points presented
// to the user. Each preset toggles a subset of optional features on.
type Preset struct {
	Name        string
	Description string
	Postgres    bool
	Valkey      bool
	WebSockets  bool
	LogLevel    string
}

var presets = []Preset{
	{
		Name:        "minimal",
		Description: "HTTP only, no datastores",
		Postgres:    false,
		Valkey:      false,
		WebSockets:  false,
		LogLevel:    "info",
	},
	{
		Name:        "standard",
		Description: "HTTP + Postgres + Valkey cache",
		Postgres:    true,
		Valkey:      true,
		WebSockets:  false,
		LogLevel:    "info",
	},
	{
		Name:        "full",
		Description: "Everything: HTTP + datastores + websockets + debug logs",
		Postgres:    true,
		Valkey:      true,
		WebSockets:  true,
		LogLevel:    "debug",
	},
}

// presetByName returns the preset with the given name, or nil if no
// such preset exists.
func presetByName(name string) *Preset {
	for i := range presets {
		if presets[i].Name == name {
			return &presets[i]
		}
	}
	return nil
}

// Config is the final accumulated state from the wizard. It maps 1:1
// to the env vars consumed by cmd/server/main.go.
type Config struct {
	Port        int
	Postgres    bool
	Valkey      bool
	WebSockets  bool
	LogLevel    string
	DatabaseURL string
	ValkeyAddr  string
}

// fromPreset seeds a Config from a Preset, filling defaults for the
// fields a preset doesn't cover.
func fromPreset(p Preset) Config {
	c := Config{
		Port:       8080,
		Postgres:   p.Postgres,
		Valkey:     p.Valkey,
		WebSockets: p.WebSockets,
		LogLevel:   p.LogLevel,
	}
	if c.Postgres {
		c.DatabaseURL = "postgres://appuser:apppass@localhost:5432/appdb?sslmode=disable"
	}
	if c.Valkey {
		c.ValkeyAddr = "localhost:6379"
	}
	return c
}

// renderEnv produces the .env file body for a Config. Disabled
// features are written as commented-out lines so users can flip them
// on later without re-running the wizard.
func renderEnv(c Config) string {
	var b strings.Builder
	b.WriteString("# Generated by `onboard`. Re-run to regenerate.\n\n")
	fmt.Fprintf(&b, "PORT=%d\n", c.Port)
	fmt.Fprintf(&b, "LOG_LEVEL=%s\n", c.LogLevel)
	fmt.Fprintf(&b, "ENABLE_WEBSOCKETS=%t\n", c.WebSockets)
	b.WriteString("\n")

	if c.Postgres {
		fmt.Fprintf(&b, "DATABASE_URL=%s\n", c.DatabaseURL)
	} else {
		b.WriteString("# DATABASE_URL=postgres://...\n")
	}
	if c.Valkey {
		fmt.Fprintf(&b, "VALKEY_ADDR=%s\n", c.ValkeyAddr)
	} else {
		b.WriteString("# VALKEY_ADDR=localhost:6379\n")
	}
	return b.String()
}

// writeConfig writes the rendered env to dir/.env, returning the
// absolute path it wrote.
func writeConfig(dir string, c Config) (string, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}
	if info, err := os.Stat(abs); err != nil || !info.IsDir() {
		return "", fmt.Errorf("target %q is not a directory", dir)
	}
	path := filepath.Join(abs, ".env")
	if err := os.WriteFile(path, []byte(renderEnv(c)), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
