name: "Commit"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  checks: write

jobs:
  compile-binary:
    runs-on: ubuntu-latest

    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4

      - name: "Compile Go binary"
        run: go build cmd/server/main.go

  build-image:
    runs-on: ubuntu-latest
    needs:
      - compile-binary
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4

      - name: "Log in to GitHub Docker registry"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: "Build Docker image"
        run: docker build -t ghcr.io/${{ github.repository_owner }}/server:latest .

      - name: "Push Docker image"
        run: docker push ghcr.io/${{ github.repository_owner }}/server:latest
